### ISSUE TITLE
AWMay2024Argus001: SAE Recon LL_IOB-013_Cumulative till 30-Apr-2024

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/AWINSA_Incident_Management_2024#1]
AWMay2024Argus001: SAE Recon LL_IOB-013_Cumulative till 30-Apr-2024 to be generated on 06-May-2024.

**Comment by vtabjul** [comment]
Sql was generated, extracted data was shared accordingly to Awinsa.

[Mail communication (SAE Recon LL_IOB-013_Cumulative till 30-Apr-2024).pdf](https://github.com/DBMS-Consulting/AWINSA_Incident_Management_2024/files/15274438/Mail.communication.SAE.Recon.LL_IOB-013_Cumulative.till.30-Apr-2024.pdf)
