### ISSUE TITLE
AWMay2024Argus003:GSK case is not reflecting in pending ICSR page after transporting the XML

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/AWINSA_Incident_Management_2024#3]
Dear Ashleen/Vishnu,

After transporting the GSK XML through FTP server (GSK Import), the case is not reflecting in the pending ICSR page

Could you please investigate this on priority.

Thanks and Regards,

Saranya P M

**Comment by vtabjul** [comment]
SR 3-36749329631 : Appropriate errors are not showing up in the error report upon E2B R3 import" was opened on 14-May-2024
